apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  volumes:
  - name: mysql-config-volume
  configMap:
    name: mysql-config
    items:
      - key: my.cnf
        path: .my.cnf
  
  containers:
  - name: mysql
    image: mysql:5.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_USER
        value: prasad
      - name: MYSQL_PASSWORD
        value: prasad
      - name: MYSQL_DATABASE
        value: prasad
    volumeMounts:
    - name: mysql-config-volume
      mountPath: /root/
