apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
      name: app-C
      environment: Development
      tier: backend

spec:
  containers:
    - name: mariadb
      image: mariadb
      env:
        - name: "MYSQL_USER"
          value: "mysql"
        - name: "MYSQL_PASSWORD"
          value: "mysql"
        - name: "MYSQL_DATABASE"
          value: "sample"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "supersecret"
      ports:
        - containerPort: 3306
