 # manifest file to display the the usage of strategy type Rolling Update


apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-application
spec:
  replicas: 5
  revisionHistoryLimit: 15
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: fleetman
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0
        resources:
          limits:
             cpu: 200m
             memory: 128Mi
             
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30008
  type: NodePort
