apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    environment: Development
    name: app-C
    tier: backend
  name: mariadbsvc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    environment: Development
    name: app-C
    tier: backend
  type: ClusterIP
status:
  loadBalancer: {}
